### ISSUE TITLE
lab3 - dubai

### ISSUE THREAD

**Issue by sstanic01** [emanuelkufrin/tvz_c-2023#1]
/*
   Opis zadatka:
   Davor i Ivica su u Dubaiu i jedan stoji s jedne strane niza zgrada, a drugi s druge.
   Potrebno je ispisati koliko koji zgrada vidi.
   Prvo se unosi n broj zgrada, a zatim za svaku zgradu visina u katovima.
   Svaka zgrada je visoka nekoliko katova i zgrade koje imaju manje katova od prethodne najviše zgrade ispred njih 
   se ne vide.

   Primjer:
   Ako su zgrade visoke 1 2 4 3 7 2 3 1 katova, iz Davorove perspektive se vide 4 zgrade (1, 2, 4, 7),
   a iz Ivicine perspektive 3 zgrade (1, 3, 7).

   P.S. Onaj koji vidi više zgrada, njegovo se ime prvo ispisuje ili ako se vidi isto zgrada onda se ispisuje prvo Davorovo.  Ako je vidljivost ista, ispisuje se prvo Davorovo ime.

   Primejer Ulaza:
   5
   1
   3
   2
   4
   3
   Primjer Izlaza:
   Davor 3
   Ivica 2
*/

#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#define MAX 100

int main()
{
    int n, davor[MAX] = {}, ivica[MAX] = {};

    // Unos broja zgrada
    scanf("%d", &n);

    int k = n;
    for (int i = 0; i < n; i++) {  
        // Unos visine zgrada iz Davorove i Ivicine perspektive.
        // Ivica je s druge strane niza pa visinu prve zgrade iz Davorove perspektive unosimo kao zadnju zgradu iz Ivicine perspektive
        scanf("%d", &davor[i]);
        ivica[k - 1] = davor[i];
        k--;
    }

    int najvisaDavor = 0, najvisaIvica = 0, vidljiveIvica = 0, vidljiveDavor = 0;
    for (int i = 0; i < n; i++) {
        if (davor[i] > najvisaDavor) { // Ako je zgrada 'i' najvisa do sad ona ce se vidjet i dodat cemo ju u vidljiveDavor
            najvisaDavor = davor[i];
            vidljiveDavor++;
        }
        if (ivica[i] > najvisaIvica) { 
            najvisaIvica = ivica[i];
            vidljiveIvica++;
        }
    }

    if (vidljiveDavor >= vidljiveIvica) {
        printf("Davor %d\n", vidljiveDavor);
        printf("Ivica %d\n", vidljiveIvica);
    }
    else {
        printf("Ivica %d\n", vidljiveIvica);
        printf("Davor %d\n", vidljiveDavor);
    }

    return 0;
}

**Comment by sstanic01** [comment]
lab3 - dubai

**Comment by emanuelkufrin** [comment]
Već dodano, hvala.
