### ISSUE TITLE
1. Kolokvij Programiranje grupa utorak part1

### ISSUE THREAD

**Issue by Miihaeel** [emanuelkufrin/tvz_c-2023#32]
#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <math.h>
/*PRVI ZADATAK KOLOKVIJ
Zadatak: unos x y a b, ispisi brojeve u intervalu[x,y) koji su dijeljivi s a ili b ali ne oba istovremeno
Nema test caseova*/

int main()
{
	int x, y, a, b;
	scanf("%d %d", &x, &y);
	scanf("%d %d", &a, &b);
	for (x; x < y; x++) {		
		if (x % a == 0 && x % b != 0) {
			printf("%d\n", x);
		}
		else if (x % a != 0 && x % b == 0) {
			printf("%d\n", x);
		}
	}
}

/*DRUGI ZADATAK KOLOKVIJ
Zadatak: Napisati program u C koji sa tipkovnice ucitava rezultate nogometnih utakmica u sljedecem formatu:
broj_tima1 broj_tima2 golovi_tima1 golovi_tima2 (na primjer 1 2 4 3)
Timova u skupini ima 5, oznaceni rednim brojevima od 1 do 5.

Ucitavanje zavrsava kada se upisu sve nule ili kada je broj prvog tima jednak broju drugog tima.

Napisati program koji ce napraviti i ispisati tablicu bodova skupine. Tablica izgleda ovako:
broj_tima Bodovi

Na kraju ispisati tim s najvi�e bodova porukom" Najvise bodova ima tim: _".
Ako ih ima vise - sve njih navesti, kao na primjer: " Najvise bodova ima tim: 3 4 5".

Napomena: pobjeda donosi 3 boda, nerijeseno 1, a poraz 0 bodova.
*/

int main() {
    int points[5] = { 0 }; 
    int team1, team2, goals1, goals2;

    while (1) {

        scanf("%d %d %d %d", &team1, &team2, &goals1, &goals2);

        if (team1 == 0 || team2 == 0 || team1 == team2) {
            break;
        }
        if (goals1 > goals2) {           
            points[team1 - 1] += 3;
        }
        else if (goals1 < goals2) {
            points[team2 - 1] += 3;
        }
        else {
            points[team1 - 1] += 1;
            points[team2 - 1] += 1;
        }
    }

    // Ispis tablice bodova
    printf("\nTablica bodova:\n");
    printf("Broj_tima  Bodovi\n");
    for (int i = 0; i < 5; i++) {
        printf("%5d  %7d\n", i + 1, points[i]);
    }

    // Pronalaženje tima s najviše bodova
    int maxPoints = 0;
    printf("\nNajvise bodova ima tim:");
    for (int i = 0; i < 5; i++) {
        if (points[i] > maxPoints) {
            maxPoints = points[i];
        }
    }

    for (int i = 0; i < 5; i++) {
        if (points[i] == maxPoints) {
            printf(" %d", i + 1);
        }
    }
    printf("\n");

    return 0;
}

**Comment by emanuelkufrin** [comment]
Dodano, zahvaljujem.
