### ISSUE TITLE
Prosjek prosjeka

### ISSUE THREAD

**Issue by dinostupar78** [emanuelkufrin/tvz_c-2023#46]
#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#define MAX 200

double prosjekBroja(int a) {
	int zbrojZn = 0;
	int brojac = 0;
	int temp = a;
	while (temp != 0) {
		zbrojZn += temp % 10;
		temp /= 10;
		brojac++;
	}
	double prosjekBroja = (double)zbrojZn / brojac;
	return prosjekBroja;
}

int main()
{
	int n, counter = 0;
	double prosjekProsjeka = 0;
	long long int niz[MAX];
	scanf("%d", &n);
	while (n < 1 || n>100) {
		printf("Nepravilan unos!\n");
		scanf("%d", &n);
	}
	for (int i = 0; i < n; i++) {
		scanf("%lld", &niz[i]);
		counter++;
	}
	// bubble sort
	for (int i = 0; i < n; i++) {
		for (int j = i + 1; j < n; j++) {
			if (niz[j] > niz[i]) {
				int temp = niz[i];
				niz[i] = niz[j];
				niz[j] = temp;
			}
		}
	}

	printf("Prosjek prosjeka: ");
	for (int i = 0; i < n; i++) {
		 prosjekProsjeka += prosjekBroja(niz[i]) / counter;
		 

	}
	printf("%.2f", prosjekProsjeka);
	printf("\nProsjeci brojeva: ");
	for (int i = 0; i < n; i++) {
		double prosjekBrojeva = prosjekBroja(niz[i]);
		printf("%.2f ", prosjekBrojeva);
	}
	
}

**Comment by emanuelkufrin** [comment]
Dodao sam.
