### ISSUE TITLE
lokvice i djecica

### ISSUE THREAD

**Issue by ivanjur03** [emanuelkufrin/tvz_c-2023#5]
#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>

int main() {
	int N;
	int skup[100] = { 0 };
	int skup2[5] = { 0 };
	scanf("%d", &N);
	for (int i = 0; i < N; i++) {
		scanf("%1d", &skup[i]);

	}
	for (int i = 0; i < N; i++) {
		if (skup[i] == 1) {
			skup2[0]++;

		}
		if (skup[i] == 2) {
			skup2[1]++;

		}
		if (skup[i] == 3) {
			skup2[2]++;

		}
		if (skup[i] == 4) {
			skup2[3]++;

		}
		if (skup[i] == 5) {
			skup2[4]++;

		}

	}
	
	
	//odredimo max od skup2
	int max = skup2[0];
	int najmetar = 1;
	for (int i = 1; i < 5; i++) {
		if (skup2[i] > max) {
			max=skup2[i];
			najmetar = i + 1;
		}
		
	}
	int cnt = 0;
	for (int i = 0; i < 5; i++) {
		if(skup2[i]==max){
			cnt++;
		}
	}
	if (cnt == 1) {

		printf("Najbolje je stati na %d. metar, gazi se ukupno u %d lokvi.", najmetar, max);
	}
	else {
		printf("Nema pobjednika, cekaj iducu kisu.");
	}
	
}

**Comment by emanuelkufrin** [comment]
Dodano, zavhaljujem.
