### ISSUE TITLE
Zadatak - ProšleGod

### ISSUE THREAD

**Issue by vincelj5** [emanuelkufrin/tvz_c-2023#67]
#define _CRT_SECURE_NO_WARNINGS

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#define MAX 100

int strlen1(char* jmbg)
{
    int br = 0;
    int tmp = 0;

    while (jmbg[tmp] != '\0')
    {  
        if (islower(jmbg[tmp]))
        {
            br++;
        }
        tmp++;
    }
    return br;
}

int main()
{
    char** poruke = NULL;
    poruke = (char**)calloc(2, sizeof(char*));

    int br1 = 0;
    int br2 = 0;

    for (int i = 0; i < 2; i++)
    {
        poruke[i] = (char*)calloc(1000, sizeof(char));
    }

    scanf("%[^\n]%*c", poruke[0]);
    scanf("%[^\n]%*c", poruke[1]);

    br1 = strlen1(poruke[0]);
    br2 = strlen1(poruke[1]);

    printf("%d i %d", br1, br2);

    return 0;
}

**Comment by emanuelkufrin** [comment]
Oprostite kolega koji je ovo zadatak sa prošle god? Navedite ime. 
Liči na onaj sa prebrojavanjem malih slova, ali odkud JMBG?

**Comment by vincelj5** [comment]
Ma to je onaj strlen, u kojem se ne smije koristiti biblioteka string.h
nemam vremena za dodat sad

sri, 20. pro 2023. u 22:36 Kritinq ***@***.***> napisao je:

**Comment by emanuelkufrin** [comment]
Dodano, zamjenio sam jmbg sa 's' da ne buni ostale kolege.
