### ISSUE TITLE
ispravljeni zadatak "datum" s labosa ovog tjedna

### ISSUE THREAD

**Issue by mislavil** [emanuelkufrin/tvz_c-2023#68]
//radi zadnji test case, ne corrupta zadnji broj, free-a memoriju

#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

char* datumizacija(char* dat, char* pred)
{
	int duljina = strlen(dat);
	int brojmj = 0;
	int brojdan = 0;
	int brojgod = 0;
	int flag = 0;
	char mjeseci[5] = { 0 };
	char dani[5] = { 0 };
	char godine[6] = { 0 };
	char* gotovi = (char*)calloc(20, sizeof(char));

	for (int i = 0; i < duljina; i++)
	{
		if (pred[i] == 'm')
		{
			mjeseci[brojmj] = dat[i];
			brojmj++;
		}
		else if (pred[i] == 'd')
		{
			dani[brojdan] = dat[i];
			brojdan++;
		}
		else if (pred[i] == 'g')
		{
			godine[brojgod] = dat[i];
			brojgod++;
			flag = i;
		}
	}

	if (brojgod == 1)
	{
		godine[1] = dat[flag+1];
	}

	if (strlen(dani) == 1)
	{
		dani[1] = dani[0];
		dani[0] = '0';
		dani[2] = '.';
	}
	else if (strlen(dani) == 2)
	{
		dani[2] = '.';
	}

	if (strlen(mjeseci) == 1)
	{
		mjeseci[1] = mjeseci[0];
		mjeseci[0] = '0';
		mjeseci[2] = '.';
	}
	else if (strlen(mjeseci) == 2)
	{
		mjeseci[2] = '.';
	}

	if (strlen(godine) == 2)
	{
		godine[2] = godine[0];
		godine[3] = godine[1];
		godine[0] = '2';
		godine[1] = '0';
		godine[4] = '.';
	}

	strcat(gotovi, dani);
	strcat(gotovi, mjeseci);
	strcat(gotovi, godine);

	return gotovi;
}

int main()
{
	char datum[20] = { 0 };
	char predlozak[20] = { 0 };
	char* rjesenje = 0;

	scanf("%s", datum);
	scanf("%s", predlozak);

	rjesenje = datumizacija(datum, predlozak);

	printf("%s", rjesenje);

	free(rjesenje);

	return 0;
}

**Comment by emanuelkufrin** [comment]
Zahvaljujem, ispravljeno.
