### ISSUE TITLE
Prošlogodišnji Ime i prezime dijagonalno

### ISSUE THREAD

**Issue by gabrielbezj** [emanuelkufrin/tvz_c-2023#69]
#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <math.h>

void spoji(char* ime_prez, char* ime, char* prezime)
{
    strcat(ime_prez, ime);
    strcat(ime_prez, " ");
    strcat(ime_prez, prezime);
    strcat(ime_prez, ".");
}

void ispis(char* ime, char* prezime)
{

    int duljina;
    int imeInd = 0;
    int prezimeInd = 0;
    if (strlen(ime) > strlen(prezime))
    {
        duljina = strlen(ime);
    }
    else
    {
        duljina = strlen(prezime);
    }
    for (int i = 0; i < duljina; i++)
    {
        for (int j = 0; j < i + 1; j++)
        {
            printf(" ");
        }
        if (i < strlen(prezime))
        {
            printf("%c", prezime[i]);
        }
        else
        {
            printf(" ");
        }
        printf("           ");
        if (i < strlen(ime))
        {
            printf("%c\n",ime[i]);
        }
        else
        {
            printf(" \n");
        }
    }
}

int main()
{
    char Ime[36 + 1];
    char Prez[36 + 1];
    int duljina = 0;

    printf("Unesi ime\n");
    scanf("%[^\n]%*c", Ime);
    printf("Unesi prezime\n");
    scanf("%[^\n]%*c", Prez);

    char* ime_prez = (char*)calloc(strlen(Ime) + strlen(Prez), sizeof(char));
    spoji(ime_prez, Ime, Prez);
    duljina = strlen(ime_prez);
    printf("%s %d\n", ime_prez, duljina);
    printf("%s %s\n", Prez, Ime);
    ispis(Ime, Prez);

    return 0;
}

**Comment by emanuelkufrin** [comment]
Malo sam modificirao i dodao, zahvaljujem.
Npr umjesto ovog dugackog praznog printf, samo se u imenu stavi %15c.
