### ISSUE TITLE
Lab 3 - Polja i Petlje 3

### ISSUE THREAD

**Issue by dinostupar78** [emanuelkufrin/tvz_c-2023#7]
/*Napisati program koji u jednodimenzionalno polje cijelih brojeva naziva poljeA pohranjuje 10 brojeva učitanih putem
tipkovnice. Program nakon pohrane brojeva korisniku nudi opciju odabira između tri mogućnosti:
1. Broj_negativnih – u polju poljeA potrebno je prebrojati koliko ima negativnih brojeva i ispisati podatak na ekran
2. Sortiranje polja – u novo polje naziva poljeB potrebno je pohraniti samo parne vrijednosti iz polja poljeA silazno
sortirane i ispisati oba polja
3. Prijepis polja – u novo polje naziva poljeC potrebno je pohraniti one vrijednosti iz poljaA čiji zbroj znamenaka nije veći
od broja 10, te ispisati oba polja*/

#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#define MAX 100
int main()
{
	int n = 10, poljeA[MAX],poljeB[MAX], poljeC[MAX], temp[MAX], odabir, br_negativnih = 0, j = 0;
	for (int i = 0; i < n; i++) {
		scanf("%d", &poljeA[i]);
	}
	scanf("%d", &odabir);
	switch (odabir) {
	case 1:
		for (int i = 0; i < n; i++) {
			if (poljeA[i] < 0)
				br_negativnih++;

		}
		printf("U polju poljeA negativnih brojeva ima: %d", br_negativnih);
		break;
	case 2:
		printf("PoljeA (nesortirano): ");
		for (int i = 0; i < n; i++) {
			printf("%d ", poljeA[i]);
		}
		printf("\nPoljeB (sortirano): ");
		
		for (int i = 0; i < n; i++) {
			if (poljeA[i] % 2 == 0) {
				poljeB[j] = poljeA[i];
				j++;
			}	
		}
		
		for (int i = 0; i < j - 1; i++) {
			for (int k = i + 1; k < j; k++) {
				if (poljeB[i] < poljeB[k]) {
					int temp = poljeB[i];
					poljeB[i] = poljeB[k];
					poljeB[k] = temp;
				}
			}
		}
		for (int i = 0; i < j; i++) {
			printf("%d ", poljeB[i]);
		}
		break;
	case 3:
		printf("PoljeA: ");
		for (int i = 0; i < n; i++) {
			printf("%d ", poljeA[i]);
		}
		
		printf("\nPoljeC: ");
		for (int i = 0; i < n; i++) {
			poljeC[i] = poljeA[i];
			int temp = poljeC[i];
			int zbroj = 0;
			while (temp != 0) {
				zbroj += temp % 10;
				temp /= 10;
			}

			if (zbroj <= 10) {
				printf("%d ", poljeC[i]);
			}
		}
		break;
	default:
		break;
	}
}

**Comment by emanuelkufrin** [comment]
Dodano, zahvaljujem.
