### ISSUE TITLE
Vjezba za lab 8 - Nogomet

### ISSUE THREAD

**Issue by mislavil** [emanuelkufrin/tvz_c-2023#73]
#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

struct tim 
{
	char naziv[40] = { 0 };
	int brojutakmica;
	int pobjede;
	int nerjeseni;
	int porazi;
	int ukupnibodovi;
};

int main()
{
	FILE* klubovi = fopen("nogometi.txt", "r");

	char nazivtima[40] = { 0 };
	char nazivdrugogtima[40] = { 0 };
	int rez1 = 0;
	int rez2 = 0;
	int flag1 = 0;
	int flag2 = 0;
	int brojactimova = 0;
	int timindex = 0;
	int najbodovi = 0;

	tim timovi[18] = { 0 };
	
	while (fscanf(klubovi, "%[^#]#%[^#]#%d:%d\n", nazivtima, nazivdrugogtima, &rez1, &rez2) == 4)
	{
		flag1 = 0;
		flag2 = 0;

		for (int i = 0; i < 18; i++)
		{
			if (strcmp(timovi[i].naziv, nazivtima) == 0)
			{
				flag1++;
				timovi[i].brojutakmica++;
				if (rez1 > rez2)
				{
					timovi[i].pobjede++;
					timovi[i].ukupnibodovi += 3;
				}
				else if (rez1 == rez2)
				{
					timovi[i].nerjeseni++;
					timovi[i].ukupnibodovi += 1;
				}
				else
				{
					timovi[i].porazi++;
				}
			}

			if (strcmp(timovi[i].naziv, nazivdrugogtima) == 0)
			{
				flag2++;
				timovi[i].brojutakmica++;
				if (rez1 < rez2)
				{
					timovi[i].pobjede++;
					timovi[i].ukupnibodovi += 3;
				}
				else if (rez1 == rez2)
				{
					timovi[i].nerjeseni++;
					timovi[i].ukupnibodovi += 1;
				}
				else
				{
					timovi[i].porazi++;
				}
			}
		}

		if (flag1 == 0)
		{
			strcpy(timovi[brojactimova].naziv, nazivtima);
			timovi[brojactimova].brojutakmica++;
			if (rez1 > rez2)
			{
				timovi[brojactimova].pobjede++;
				timovi[brojactimova].ukupnibodovi += 3;
			}
			else if (rez1 == rez2)
			{
				timovi[brojactimova].nerjeseni++;
				timovi[brojactimova].ukupnibodovi += 1;
			}
			else
			{
				timovi[brojactimova].porazi++;
			}
			brojactimova++;
		}

		if (flag2 == 0)
		{
			strcpy(timovi[brojactimova].naziv, nazivdrugogtima);
			timovi[brojactimova].brojutakmica++;
			if (rez1 < rez2)
			{
				timovi[brojactimova].pobjede++;
				timovi[brojactimova].ukupnibodovi += 3;
			}
			else if (rez1 == rez2)
			{
				timovi[brojactimova].nerjeseni++;
				timovi[brojactimova].ukupnibodovi += 1;
			}
			else
			{
				timovi[brojactimova].porazi++;
			}
			brojactimova++;
		}
	}

	for (int i = 0; i < 18; i++)
	{
		if (timovi[i].ukupnibodovi > najbodovi)
		{
			najbodovi = timovi[i].ukupnibodovi;
			timindex = i;
		}
	}

	FILE* prvitim = fopen("prvi.txt", "w");

	fprintf(prvitim, "%s %d %d %d %d %d", timovi[timindex].naziv, timovi[timindex].brojutakmica, timovi[timindex].pobjede,
		timovi[timindex].nerjeseni, timovi[timindex].porazi, timovi[timindex].ukupnibodovi);

	fclose(klubovi);
	fclose(prvitim);

	return 0;
}

**Comment by emanuelkufrin** [comment]
Dodano, zahvaljujem.
