### ISSUE TITLE
Vjezba za lab 8 - Sigurne i nesigurne lozinke

### ISSUE THREAD

**Issue by mislavil** [emanuelkufrin/tvz_c-2023#74]
#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main()
{
	char user[40][40] = { 0 };
	char pass[40][40] = { 0 };
	char commonpasses[160][40] = { 0 };
	char password[40] = { 0 };
	int i = 0;
	int j = 0;
	int sigbrojac = 0;

	FILE* lozinke = fopen("common_passwords.txt", "r");

	while (fscanf(lozinke, "%s", password) == 1)
	{
		strcpy(commonpasses[j], password);
		j++;
	}

	while (scanf("%[^:]:%s\n", user[i], pass[i])==2)
	{
		i++;
	}

	FILE* rezultat = fopen("RezultatiAnalize.txt", "w");

	for (int n = 0; n < i; n++)
	{
		fprintf(rezultat, "%s\n", pass[n]);
	}

	fprintf(rezultat, "\n");
	fprintf(rezultat, "Popis sigurnih lozinki:\n");

	for (int k = 0; k < i; k++)
	{
		sigbrojac = 0;
		for (int m = 0; m < j; m++)
		{
			if (strcmp(pass[k], commonpasses[m]) == 0)
			{
				sigbrojac++;
			}
			if (strncmp(user[k], pass[k], 5) == 0)
			{
				sigbrojac++;
			}
		}
		if (sigbrojac == 0)
		{
			fprintf(rezultat, "%s\n", pass[k]);
		}
	}

	fclose(lozinke);

	return 0;
}

**Comment by emanuelkufrin** [comment]
Dodano, zahvaljujem,
Ubuduće molim dodati tekst zadatka bar, da ne moram tražiti.
