### ISSUE TITLE
lab8 auti brzi i skupi

### ISSUE THREAD

**Issue by PetraSenicnjak** [emanuelkufrin/tvz_c-2023#88]
#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

typedef struct {
    char proizvodac[40];
    char model[40];
    char karoserija[40];
    int volimen;
    int snaga;
    int ubrzanje;
    int brzina;
    int cijena;
}autom;

int main()
{
    FILE* dat1 = NULL;
    FILE* dat2 = NULL;
    autom popis[5000], rez[500], min = {0}, max = {0};
    int i = 0, br = 0, minu=1000000, maxc=0;

    dat1 = fopen("automobili.txt", "r");
    dat2 = fopen("brzi.txt", "w");
                       
    while (fscanf(dat1, "%[^#]#%[^#]#%[^#]#%d#%d#%d#%d#%d\n", popis[i].proizvodac, popis[i].model, popis[i].karoserija, &popis[i].volimen, &popis[i].snaga, &popis[i].ubrzanje, &popis[i].brzina, &popis[i].cijena) == 8)
    {
        i++;
    }

    for (int j = 0; j < i; j++)
    {
        if (popis[j].ubrzanje < 6 && popis[j].cijena > 1000000)
        {
            rez[br] = popis[j];
            br++;
        }
    }

    for (int i = 0; i < br; i++)
    {
        if (rez[i].cijena > maxc)
        {
            maxc = rez[i].cijena;
            max = rez[i];
        }
        if (rez[i].ubrzanje < minu)
        {
            minu = rez[i].ubrzanje;
            min = rez[i];
        }
    }

    for (int i = 0; i < br; i++)
    {
        fprintf(dat2, "%s %s %s %d %d %d %d %d\n", rez[i].proizvodac, rez[i].model, rez[i].karoserija, rez[i].volimen, rez[i].snaga, rez[i].ubrzanje, rez[i].brzina, rez[i].cijena);
    }
    fprintf(dat2, "\nnajbrzi je %s %s %s %d %d %d %d %d\n", min.proizvodac, min.model, min.karoserija, min.volimen, min.snaga, min.ubrzanje, min.brzina, min.cijena);
    fprintf(dat2, "najskuplji je %s %s %s %d %d %d %d %d", max.proizvodac, max.model, max.karoserija, max.volimen, max.snaga, max.ubrzanje, max.brzina, max.cijena);

    fclose(dat1);
    fclose(dat2);

    return 0;
}

**Comment by emanuelkufrin** [comment]
Dodano, zahvaljujem.
