### ISSUE TITLE
lab8 narudzba

### ISSUE THREAD

**Issue by PetraSenicnjak** [emanuelkufrin/tvz_c-2023#89]
/*U binarnoj datoteci katalog.dat nalaze se zapisi artikala robe u dućanu razne robe, u obliku struktura:
šifra artikla - cijeli broj,
naziv artikla - string od 54+1 znak,
cijena artikla - realni broj (float),
količina artikala u dućanu - cijeli broj.
Potrebno je napisati program kojim trgovac od dobavljača naručuje artikle upisom šifre i količine, sve dok ne upiše nulu za
šifru, a za svaki artikl se u funkciji narudzba u drugu tekstualnu datoteku narudzba.txt ispisuju podaci o naručenom artiklu i
iznos (cijena*količina), u formatu:
šifra|naziv|cijena|količina|iznos
Artiklima se u datoteci katalog.dat pristupa isključivo direktnim pristupom pomoću šifre!
Ako šifre u katalogu nema - u narudžbu se umjesto naziva i ostalih podataka napiše "Artikl ne postoji".
Ako je zbroj količina artikla na skladištu i u narudžbi veći od 30 – u narudžbu se upiše količina koja nedostaje do 30.
Na kraju se u narudžbu ispiše "Ukupna vrijednost narucene robe " i ukupni iznos koji je zbroj iznosa za naručene artikle.
*/

#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

typedef struct {
    int sifra;
    char naziv[54 + 1];
    float cijena;
    int kolicina;
}artikl;

float narudzba(artikl popis[], FILE* dat2, int i, int kol);

int main()
{
    FILE* dat1 = fopen("katalog.dat", "rb");
    FILE* dat2 = fopen("narudzba.txt", "w");
    artikl popis[1000];
    int br = 0, sifrau, kol;
    float uk = 0;

    fseek(dat1, 0, SEEK_END);
    int vel = ftell(dat1) / sizeof(artikl);
    fseek(dat1, 0, SEEK_SET);
    fread(popis, sizeof(artikl), vel, dat1);

    while (1)
    {
        br = 0;
        scanf("%d", &sifrau);

        if (sifrau == 0)
            break;

        scanf("%d", &kol);

        for (int i = 0; i < vel; i++)
        {
            if (sifrau == popis[i].sifra)
            {
                uk += narudzba(popis, dat2, i, kol);
                br = 1;
            }
            else if(i == vel-1 && br == 0)
            {
                fprintf(dat2, "Artikl ne postoji\n");
            }
        }
    }

    fprintf(dat2, "Ukupna vrijednost narucene robe %.2f", uk);

    fclose(dat1);
    fclose(dat2);

    return 0;
}

float narudzba(artikl popis[], FILE* dat2, int i, int kol)
{

    if (kol + popis[i].kolicina > 30)
        kol = 30 - popis[i].kolicina;

    float ukupno = popis[i].cijena * kol;

    fprintf(dat2, "%d|%s|%.2f|%d|%.2f\n", popis[i].sifra, popis[i].naziv, popis[i].cijena, kol, ukupno);

    return ukupno;
}

**Comment by emanuelkufrin** [comment]
Dodano, zahvaljujem.
