### ISSUE TITLE
lab8 vozacke dozvole 1

### ISSUE THREAD

**Issue by PetraSenicnjak** [emanuelkufrin/tvz_c-2023#90]
/*Potrebno je iz baze vozača izvući one koji žive u danom gradu, poredano po registraciji abecedno.
Jedan zapis u datoteci car-data.dat izgleda ovako:
char grad[100];
char reg[9]; - registracija
char name[100]; - ime vozača
char surname[100]; - prezime vozača
char street[200]; - ulica vozača
int month; - mjesec izdavanja vozačke dozvole
int day; - dan izdavanja vozačke dozvole
int year; - godina izdavanja vozačke dozvole
char category[3]; - kategorija (slovo i znamenka)*/

#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

typedef struct {
    char grad[100];
    char reg[9];
    char name[100]; 
    char surname[100];
    char street[200]; 
    int month; 
    int day; 
    int year; 
    char category[3];
}vozac;

int main()
{
    FILE* dat = NULL;
    vozac popis[1000], rez[50];
    char ulaz[100];

    dat = fopen("car-data.dat", "rb");

    scanf("%s", ulaz);

    int vel, br = 0;
    fseek(dat, 0, SEEK_END);
    vel = ftell(dat) / sizeof(vozac);
    fseek(dat, 0, SEEK_SET);
    fread(popis, sizeof(vozac), vel, dat);

    for (int i = 0; i < vel; i++)
    {
        if (strcmp(ulaz, popis[i].grad) == 0)
        {
            rez[br] = popis[i];
            br++;
        }
    }

    if (br == 0)
    {
        printf("Neoznati grad!");
        fclose(dat);
        return 0;
    }

    for (int i = 0; i < br; i++)
    {
        for (int i = 0; i < br-1; i++)
        {
            if (strcmp(rez[i].reg, rez[i + 1].reg) == 1)
            {
                vozac tmp = rez[i];
                rez[i] = rez[i + 1];
                rez[i + 1] = tmp;
            }
        }
    }

    for (int i = 0; i < br; i++)
    {
        printf("%s %s %s\n", rez[i].reg, rez[i].name, rez[i].surname);
    }

    fclose(dat);

    return 0;
}

**Comment by emanuelkufrin** [comment]
Kolegice, zadatak je bio da se ispiše u datoteku rezultat.out.
Prepravio sam Vašu grešku i dodao kod, hvala.

**Comment by PetraSenicnjak** [comment]
Sori nisam vidjela, hvala.

Poslano iz aplikacije Outlook za Android<https://aka.ms/AAb9ysg>
________________________________
