### ISSUE TITLE
Labos 8 - Grupa ČET - 18:30
Zadatak Pekara

### ISSUE THREAD

**Issue by FranLovricic** [emanuelkufrin/tvz_c-2023#92]
#define _CRT_SECURE_NO_WARNINGS
#include<stdio.h>
#include<string.h>

typedef struct {
    char proizvod[25];
    int slatkoIliSlano;
    int zaVeg;
    int kalorije;
    float cijenaKn;
}Artikl;

int main()
{
    FILE* dat1 = fopen("./pekara.txt", "r");
    FILE* dat2 = fopen("./preporuka.txt", "w");
    Artikl popis;
    Artikl najmanji;

    najmanji.cijenaKn = 9999;
    najmanji.kalorije = 9999;

    while (fscanf(dat1," %[^#]#%d#%d#%d#%f", &popis.proizvod, &popis.slatkoIliSlano, &popis.zaVeg, &popis.kalorije, &popis.cijenaKn) == 5)
    {
        
        if (strstr(popis.proizvod, "kruh") && popis.cijenaKn < 5)
        {
            if (popis.cijenaKn < najmanji.cijenaKn && popis.kalorije < najmanji.kalorije)
            {
                najmanji.cijenaKn = popis.cijenaKn;
                najmanji.kalorije = popis.kalorije;
                strcpy(najmanji.proizvod, popis.proizvod);
            }
            fprintf(dat2, "%s##%d##%.2f\n", popis.proizvod, popis.kalorije, popis.cijenaKn);
        }
    }

    fprintf(dat2, "\nNajjeftiniji kruh s najmanje kalorija je %s.", najmanji.proizvod);
    
    fclose(dat1);
    fclose(dat2);
    return 0;
}

**Comment by emanuelkufrin** [comment]
Kolega hvala na kodu, ako netko uspije poslati tekst i datoteku onda dodam, inace nema smisla.
