### ISSUE TITLE
kolokvij2 razdjelnik

### ISSUE THREAD

**Issue by PetraSenicnjak** [emanuelkufrin/tvz_c-2023#99]
/*
ulaz:
14
Prog/ramiranje
/

izlaz:
Prog 4
ramiranje 9

ulaz:
16
Prog/ram/ira/nje
/

izlaz:
Prog 4
ram/ira/nje 11

ulaz:
25
neki malo5 dulji.niz od 5
5

izlaz:
neki malo 9
 dulji.niz od 5 15

![Tekst zadatka](https://github.com/emanuelkufrin/tvz_c-2023/assets/127724927/994b4e46-2553-46e0-999d-15301de425fc)
*/

#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void razdjeli(char* recenica, char raz, char* prvi, char* drugi);

int main()
{
    int duljina;
    char* recenica, *prvi = NULL, * drugi = NULL;
    char raz;

    scanf("%d\n", &duljina);

    recenica = (char*)calloc(duljina, sizeof(char));
    prvi = (char*)calloc(duljina, sizeof(char));
    drugi = (char*)calloc(duljina, sizeof(char));

    scanf("%[^\n]\n%c", recenica, &raz);

    razdjeli(recenica, raz, prvi, drugi);

    int d1 = strlen(prvi);
    int d2 = strlen(drugi);

    printf("%s %d\n%s %d", prvi, d1, drugi, d2);

    return 0;
}

void razdjeli(char* recenica, char raz, char* prvi, char* drugi)
{
    int nasao = 0, br1 = 0, br2 = 0;
    for (int i = 0; i < strlen(recenica); i++)
    {
        if (recenica[i] == raz && nasao == 0)
        {
            nasao = 1;
            continue;
        }
        
        if (nasao == 0)
        {
            prvi[br1] = recenica[i];
            br1++;
        }
        else if (nasao == 1)
        {
            drugi[br2] = recenica[i];
            br2++;
        }
    }
}

**Comment by emanuelkufrin** [comment]
Kolegice taman sam i ja objavio prije koju minutu :)
